python run.py \
 -face_comparer_config configs/arcface_adv.yml \
 -output_dir runs/arcface_adv_reconstruct_pairs_control \
 -overwrite \
 -duplicates=8 \
 -loss_str=100*L2+0.05*GEOCROSS \
 -input_prefix=000 \
 -input_dir=CelebA_small/celeba/img_align_celeba \
 -targets_dir=CelebA_large/celeba/img_align_celeba \
 -gpu_id=6 \
 -copy_target \
 -celeba_pairs
