trainer_params:
  fast_dev_run: False
model_params:
  face_comparer_params:
    hidden_dims: []
    initial_bias: -55
    feature_extractor_model: 'arcface'
    feature_normalization_mode: 3
    feature_extractor_params:
      # model_path: 'InsightFace_v2/pretrained/BEST_checkpoint_101_20200831.tar'
      model_path: 'InsightFace_v2/pretrained/BEST_checkpoint_101_adv_20200908.tar'
  milestones: [-1, -1]
checkpoint_params:
  save_last: True
  filepath: 'saved_models/arcface_adv_agr'