trainer_params: {}
model_params:
  face_comparer_params:
    hidden_dims: []
    initial_bias: -21
  milestones: [100000, 200000]
checkpoint_params:
  save_last: True
  filepath: 'saved_models/linear_basic'